//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip_Adviser
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_OFFER
    {
        public int HotelOfferId { get; set; }
        public int HotelId { get; set; }
        public string HotelOfferTitle { get; set; }
        public string HotelOfferDesc { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
    }
}
