//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip_Adviser
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANT_OFFER
    {
        public int ResOfferId { get; set; }
        public int ResId { get; set; }
        public string ResOfferTitle { get; set; }
        public string ResOfferDesc { get; set; }
    
        public virtual RESTAURANT RESTAURANT { get; set; }
    }
}
