//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trip_Adviser
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_RATING
    {
        public int ReviewRatingId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> ResId { get; set; }
        public Nullable<int> FoodId { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual FOOD FOOD { get; set; }
        public virtual HOTEL HOTEL { get; set; }
        public virtual PLACE PLACE { get; set; }
        public virtual RESTAURANT RESTAURANT { get; set; }
    }
}
